apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions
  template:
    metadata:
      labels:
        app: transactions
    spec:
      containers:
      - name: transactions-container
        image: transactions_service:1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: transactions-service
spec:
  type: ClusterIP
  selector:
    app: transactions
  ports:
    - port: 80

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: transactions-mysql-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/soa-transactions-mysql-data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transactions-mysql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: loveiasa222
        - name: MYSQL_DATABASE
          value: transactions_service
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: transactions-mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  type: ClusterIP
   
